---
hermes_user: hermes
hermes_user_shell: /bin/bash
hermes_user_groups:
  - sudo

hermes_ssh_public_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINh3vrq0q6G1P84MspDmsA6tygUvg4lZPtjGKMHpWd5p cdqt98@gmail.com"

hermes_install_script: "https://hermes-agent.nousresearch.com/install.sh"
